name: Pull Request Body Validator

on:
  pull_request:
    types: [opened, edited]

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
    - name: Check PR Body
      id: pr_body
      run: echo '${{ toJSON(github.event) }} | jq
      shell: bash
