name: Pull Request Body Validator

on:
  pull_request:
    types: [opened, edited]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
    - name: "Check PR Body"
      run: echo '${{ toJSON(github.event) }} | jq
      shell: bash
